const app={state:{},phone:"",video:"",view:localStorage.getItem("emulation-view")||"dashboard",phoneHash:"",videoHash:"",preview:""};

// Keep playback audio preference across video changes and panel reloads.
function setupPlaybackMute(){
  const player=document.getElementById("preview");
  const label=document.createElement("label");
  label.className="check";
  label.innerHTML='<input id="playback-muted" type="checkbox"><span></span>Reproduzir no mudo';
  document.querySelector(".install-box").prepend(label);
  const toggle=label.querySelector("input");
  const saved=localStorage.getItem("emulation-playback-muted")==="true";
  player.defaultMuted=saved;
  player.muted=saved;
  toggle.checked=saved;
  toggle.addEventListener("change",()=>{
    player.muted=toggle.checked;
    player.defaultMuted=toggle.checked;
    localStorage.setItem("emulation-playback-muted",String(toggle.checked));
  });
  player.addEventListener("volumechange",()=>{
    toggle.checked=player.muted;
    player.defaultMuted=player.muted;
    localStorage.setItem("emulation-playback-muted",String(player.muted));
  });
}
setupPlaybackMute();
const $=id=>document.getElementById(id);const esc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function icons(){if(window.lucide)window.lucide.createIcons({attrs:{"stroke-width":1.8}})}
function formatTime(seconds,compact=false){seconds=Math.max(0,Number(seconds)||0);const h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60);return compact?`${h}h ${String(m).padStart(2,"0")}min`:`${String(Math.floor(seconds/60)).padStart(2,"0")}:${(seconds%60).toFixed(1).padStart(4,"0")}`}
function size(bytes){if(!bytes)return "0 MB";return bytes>=1073741824?`${(bytes/1073741824).toFixed(1)} GB`:`${(bytes/1048576).toFixed(1)} MB`}
function duration(seconds){const m=Math.floor((seconds||0)/60),s=Math.floor((seconds||0)%60);return `${m}:${String(s).padStart(2,"0")}`}
function toast(text){const el=$("toast");el.textContent=text;el.classList.add("show");clearTimeout(app.toastTimer);app.toastTimer=setTimeout(()=>el.classList.remove("show"),2800)}
async function call(action,data={}){const response=await fetch("/api/action",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...data,action})});const body=await response.json();if(!response.ok)throw Error(body.error||"Não foi possível concluir");return body}
async function act(action,data){try{await call(action,data);toast("Comando enviado");setTimeout(refresh,250)}catch(error){toast(error.message)}}
function showView(name){if(!document.getElementById(`view-${name}`))name="dashboard";app.view=name;localStorage.setItem("emulation-view",name);document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===`view-${name}`));document.querySelectorAll(".nav-item").forEach(v=>v.classList.toggle("active",v.dataset.view===name));const labels={dashboard:"Visão geral",devices:"Celulares",videos:"Vídeos",automation:"Automação"};$("crumb").textContent=labels[name];$("sidebar").classList.remove("open");$("mobile-overlay").classList.remove("show");icons()}
function empty(icon,title,text){return `<div class="empty-state"><div><i data-lucide="${icon}"></i><strong>${title}</strong><span>${text}</span></div></div>`}
function renderWeek(rows=[]){const max=Math.max(1,...rows.map(x=>x.seconds));$("week-chart").innerHTML=rows.map(x=>{const date=new Date(`${x.date}T12:00:00`),day=date.toLocaleDateString("pt-BR",{weekday:"short"}).replace(".","");return `<div class="day-column"><strong>${formatTime(x.seconds,true)}</strong><div class="day-bar-track"><i class="day-bar" style="height:${Math.max(x.seconds?5:0,x.seconds/max*100)}%"></i></div><span>${esc(day)}</span></div>`}).join("")}
function renderUsage(analytics){const tasks=analytics.byTask||[];$("task-usage").innerHTML=tasks.length?tasks.slice(0,5).map(x=>`<div class="usage-row"><header><span>${esc(x.name)}</span><strong>${formatTime(x.seconds,true)} / ${formatTime(x.limit,true)}</strong></header><div class="mini-track"><i style="width:${Math.min(100,x.seconds/Math.max(1,x.limit)*100)}%"></i></div></div>`).join(""):empty("clock","Nenhum tempo registrado","As tarefas salvas hoje aparecerão aqui");const phones=analytics.byPhone||[];const max=Math.max(1,...phones.map(x=>x.seconds));$("phone-usage").innerHTML=phones.length?phones.map(x=>`<div class="usage-row"><header><span>${esc(x.name)}</span><strong>${formatTime(x.seconds,true)}</strong></header><div class="mini-track"><i style="width:${x.seconds/max*100}%"></i></div></div>`).join(""):empty("smartphone","Nenhum celular encontrado","")}
function renderPhones(phones){const hash=JSON.stringify([app.phone,phones]);if(hash===app.phoneHash)return;app.phoneHash=hash;$("phones").innerHTML=phones.length?phones.map(p=>`<article class="phone-card ${p.serial===app.phone?"selected":""}" data-serial="${esc(p.serial)}"><div class="phone-top"><span class="device-visual"></span><span class="pill ${esc(p.status)}">${p.status==="online"?"ONLINE":p.status==="booting"?"INICIANDO":"DESLIGADO"}</span></div><h3>${esc(p.name)}</h3><small>${esc(p.serial)} • porta ${esc(p.port)}</small><div class="phone-actions"><button data-action="start"><i data-lucide="power"></i> Ligar</button><button data-action="stop"><i data-lucide="power-off"></i> Desligar</button><button class="open-minute" data-action="minute"><i data-lucide="external-link"></i> Abrir Minute</button></div></article>`).join(""):empty("smartphone","Nenhum celular configurado","Adicione um celular para começar");document.querySelectorAll(".phone-card").forEach(card=>card.addEventListener("click",event=>{app.phone=card.dataset.serial;const action=event.target.closest("[data-action]")?.dataset.action;if(action)act(action,{serial:app.phone});app.phoneHash="";renderPhones(app.state.phones||[]);updateSelectionLabels()}));icons()}
function setPreview(item){const player=$("preview"),emptyEl=$("player-empty");if(!item){player.removeAttribute("src");player.removeAttribute("poster");player.load();emptyEl.classList.remove("hidden");$("preview-name").textContent="Nenhum vídeo selecionado";$("preview-meta").textContent="—";return}$("preview-name").textContent=item.name;$("preview-meta").textContent=`${duration(item.duration)} • ${item.width||"?"}×${item.height||"?"} • ${String(item.codec||"codec desconhecido").toUpperCase()} • ${size(item.size)}`;player.poster=item.thumb;if(!item.previewReady){emptyEl.classList.remove("hidden");emptyEl.innerHTML='<div><i data-lucide="loader-circle"></i><strong>Preparando prévia compatível</strong><span>O vídeo original continua disponível normalmente</span></div>';if(player.getAttribute("src")){player.removeAttribute("src");player.load()}icons();return}emptyEl.classList.add("hidden");const key=item.name+item.playback;if(app.preview!==key){app.preview=key;player.src=item.playback||item.media;player.load()}}
function renderVideos(videos){const hash=JSON.stringify([app.video,videos]);if(hash!==app.videoHash){app.videoHash=hash;$("videos").innerHTML=videos.length?videos.map(v=>`<article class="video-card ${v.name===app.video?"selected":""}" data-video="${encodeURIComponent(v.name)}"><img class="video-thumb" src="${esc(v.thumb)}" alt="Prévia de ${esc(v.name)}" loading="lazy"><div class="video-copy"><strong>${esc(v.name)}</strong><span>${duration(v.duration)} • ${size(v.size)} • ${esc((v.codec||"vídeo").toUpperCase())}</span></div></article>`).join(""):empty("clapperboard","Biblioteca vazia","Importe o primeiro vídeo");document.querySelectorAll(".video-card").forEach(card=>card.addEventListener("click",()=>{app.video=decodeURIComponent(card.dataset.video);app.videoHash="";renderVideos(app.state.videos||[])}));icons()}setPreview(videos.find(v=>v.name===app.video));$("video-count").textContent=`${videos.length} vídeo${videos.length===1?"":"s"}`}
function updateSelectionLabels(){const p=(app.state.phones||[]).find(x=>x.serial===app.phone);$("selected-phone-label").textContent=p?`Selecionado: ${p.name}`:"Nenhum selecionado"}
function render(state){app.state=state;if(!app.phone&&state.phones[0])app.phone=state.phones[0].serial;if(!state.phones.some(p=>p.serial===app.phone)&&state.phones[0])app.phone=state.phones[0].serial;if(!app.video&&state.videos[0])app.video=state.currentName&&state.videos.some(v=>v.name===state.currentName)?state.currentName:state.videos[0].name;if(!state.videos.some(v=>v.name===app.video)&&state.videos[0])app.video=state.videos[0].name;const online=state.phones.filter(p=>p.status==="online").length,analytics=state.analytics||{};$("online").textContent=`${online} / ${state.phones.length}`;$("online-note").textContent=online===state.phones.length&&online?"Todos operacionais":online?`${state.phones.length-online} indisponível(is)`:"Nenhum conectado";$("nav-online").textContent=online;$("nav-videos").textContent=state.videos.length;$("today-hours").textContent=formatTime(analytics.todaySeconds,true);$("task-count").textContent=analytics.activeTasks||0;$("current").textContent=state.currentName||(state.current?"Vídeo ativo":"Nenhum");$("current-size").textContent=state.current?`${size(state.current)} instalado`:"Nenhum arquivo ativo";$("detected").textContent=state.task||"Aguardando a gravação";$("timer").innerHTML=`${formatTime(state.elapsed)} <span>/ ${formatTime(state.total)}</span>`;$("syncbar").style.width=`${state.progress||0}%`;$("jobbar").style.width=`${state.progress||0}%`;$("timer-percent").textContent=`${state.progress||0}%`;$("percent").textContent=`${state.progress||0}%`;$("message").textContent=state.message;$("operation-label").textContent=state.busy?"Operação em andamento":"Sistema pronto";const badge=$("badge");badge.textContent=state.level==="error"?"ERRO":state.busy?"EM CURSO":"OK";badge.style.color=state.level==="error"?"var(--red)":state.level==="warn"?"var(--amber)":"var(--green)";$("adjust-context").textContent=state.task?`${state.task} • ${((state.phones||[]).find(x=>x.serial===app.phone)||{}).name||"celular selecionado"}`:"A tarefa aparecerá após ser detectada.";renderWeek(analytics.last7Days||[]);renderUsage(analytics);renderPhones(state.phones||[]);renderVideos(state.videos||[]);updateSelectionLabels();icons()}
async function refresh(){try{const response=await fetch("/api/state",{cache:"no-store"});if(!response.ok)throw Error();render(await response.json())}catch{const badge=$("badge");badge.textContent="OFFLINE";badge.style.color="var(--red)"}}
document.querySelectorAll(".nav-item").forEach(btn=>btn.addEventListener("click",()=>showView(btn.dataset.view)));document.querySelectorAll("[data-go]").forEach(btn=>btn.addEventListener("click",()=>showView(btn.dataset.go)));$("menu-toggle").onclick=()=>{$("sidebar").classList.toggle("open");$("mobile-overlay").classList.toggle("show")};$("mobile-overlay").onclick=()=>showView(app.view);$("all").onclick=()=>act("all_start");$("add").onclick=()=>act("add");$("sync").onclick=()=>act("sync");$("cancel").onclick=()=>act("cancel");$("install").onclick=()=>app.video?act("install",{serial:app.phone,video:app.video,fill:$("fill").checked}):toast("Selecione um vídeo");document.querySelectorAll("[data-c]").forEach(btn=>btn.onclick=()=>act("control",{serial:app.phone,control:btn.dataset.c}));$("adjust").onclick=()=>app.state.task?act("adjust",{serial:app.phone,minutes:Number($("minutes").value)}):toast("Aguarde a tarefa ser detectada");
$("install-all").onclick=()=>app.video?act("install_all",{video:app.video,fill:$("fill").checked}):toast("Selecione um vídeo");
$("upload").onchange=async event=>{const file=event.target.files[0];if(!file)return;toast("Importando vídeo...");try{const response=await fetch("/api/upload",{method:"POST",headers:{"X-Filename":encodeURIComponent(file.name),"Content-Length":String(file.size)},body:file});const body=await response.json();if(!response.ok)throw Error(body.error);app.video=body.name;app.videoHash="";toast("Vídeo importado");await refresh()}catch(error){toast(error.message)}event.target.value=""};
$("preview").addEventListener("error",()=>{$("player-empty").classList.remove("hidden");$("player-empty").innerHTML='<div><i data-lucide="image"></i><strong>Miniatura disponível</strong><span>Este codec não reproduz diretamente no navegador</span></div>';icons()});$("today-label").textContent=new Date().toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long"});showView(app.view);icons();refresh();setInterval(refresh,1800);
